name: term_ask
description: A simple gemini client for the terminal
version: 1.0.0
repository: https://github.com/darkard2003/term_ask.git

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  google_generative_ai: ^0.4.6
  console_markdown: ^0.0.3
  dotenv: ^4.2.0
  args: ^2.6.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
